#include "i2s.h"
#include "driver/i2s_std.h"
#include <stdio.h>

// includes needed for task delete, see if there's another way
// to do this?
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/portmacro.h" // for portMAX_DELAY

// #include "driver/periph_ctrl.h" // for disabling peripheral

// ESP defined GPIO pins used for i2s 1
#define I2S_BCLK_IO1 GPIO_NUM_27 // I2S bit clock io number
#define I2S_WS_IO1 GPIO_NUM_26   // I2S word select io number
#define I2S_DOUT_IO1 GPIO_NUM_25 // I2S data out io number

// I2S rx channel handler
static i2s_chan_handle_t tx_chan;

// Flag to check if system is enabled before trying to
// write to the peripheral.
static bool is2_enabled = false;

// Static function definitions:
static bool esp32_i2s_init(uint32_t sample_rate, uint8_t bits_per_sample, uint8_t channels);
static void esp32_i2s_deinit();
static void esp32_i2s_write(int16_t *data_buf, size_t buf_len);

// Struct to match with our subsystem i2s wrapper,
// This is to allow this driver code to be hot-swappable
// for other drivers.
static const i2s_ops_t esp32_i2s_ops = {
    .init = esp32_i2s_init,
    .deinit = esp32_i2s_deinit,
    .write = esp32_i2s_write,
};

// When this is called, subsystem/i2s will use this esp32 driver code.
void i2s_driver_register_esp32(void)
{
    i2s_register_ops(&esp32_i2s_ops);
}

/**
 * @brief Enable the I2S hardware peripheral.
 *
 * @param sample_rate The sample read to be interpreted to audio reads and writes. This can have
 *     values of 0, 8, 16, 24, or 32.
 *
 * @param bits_per_sample Indicates the bit-width of each audio sample the will be written or
 *     or read on this channel.
 *
 * @param channels Integer determing the number of channels to initialize the peripheral with.
 *     This epects values 1 or 2.
 *
 * @return true if successful, false on error
 */
static bool esp32_i2s_init(uint32_t sample_rate, uint8_t bits_per_sample, uint8_t channels)
{
    if (is2_enabled)
    {
        printf("INFO: %s I2s channel already enabled\r\n", __func__);
        return false;
    }

    if (sample_rate != 44100)
    {
        printf("WARNING: %s Sample rate NOT 44100, functionality untested, val = %lu \r\n", __func__, sample_rate);
    }

    if (bits_per_sample != I2S_SLOT_BIT_WIDTH_AUTO &&
        (bits_per_sample != I2S_SLOT_BIT_WIDTH_8BIT) &&
        (bits_per_sample != I2S_SLOT_BIT_WIDTH_16BIT) &&
        (bits_per_sample != I2S_SLOT_BIT_WIDTH_24BIT) &&
        (bits_per_sample != I2S_SLOT_BIT_WIDTH_32BIT))
    {
        printf("ERROR: %s Invalid bit-width, val = %d, i2s not initialized \r\n", __func__, bits_per_sample);
        return false;
    }

    if ((channels != I2S_SLOT_MODE_MONO) && (channels != I2S_SLOT_MODE_STEREO))
    {
        printf("ERROR: %s Invalid number of channels, val = %d \r\n", __func__, channels);
        return false;
    }

    /* Setp 1: Determine the I2S channel configuration and allocate two channels one by one
     * The default configuration can be generated by the helper macro,
     * it only requires the I2S controller id and I2S role
     * The tx and rx channels here are registered on different I2S controller,
     * Except ESP32 and ESP32-S2, others allow to register two separate tx & rx channels on a same controller */
    i2s_chan_config_t tx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_0, I2S_ROLE_MASTER);
    tx_chan_cfg.dma_frame_num = 512; // TODO: consider changing based on latency concerns
    tx_chan_cfg.dma_desc_num = 4;    // TODO: consider changing based on latency concerns
    // tx_chan_cfg.allow_pd = ESP_INTR_FLAG_LEVEL1; // HIGH PRIORITY INTERRUPTING!
    ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));

    i2s_std_slot_config_t my_slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(bits_per_sample, channels);

    /* Step 2: Setting the configurations of standard mode and initialize each channels one by one
     * The slot configuration and clock configuration can be generated by the macros
     * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
     * They can help to specify the slot and clock configurations for initialization or re-configuring */
    i2s_std_config_t tx_std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(sample_rate),
        .slot_cfg = my_slot_cfg,
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED, // some codecs may require mclk signal, this example doesn't need it
            .bclk = I2S_BCLK_IO1,
            .ws = I2S_WS_IO1,
            .dout = I2S_DOUT_IO1,
            .din = I2S_GPIO_UNUSED, // TOOD: should use the default IO1??
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &tx_std_cfg));

    ESP_ERROR_CHECK(i2s_channel_enable(tx_chan));

    is2_enabled = true;

    return true;
}

static void esp32_i2s_deinit()
{
    if (!is2_enabled)
    {
        printf("WARNING: %s i2s channel not enabled, can't deinit\r\n", __func__);
        return;
    }

    // Halt DMA and data flow
    i2s_channel_disable(tx_chan);

    // Delete/Free the channel handle
    i2s_del_channel(tx_chan);

    // Disable the I2S peripheral (Hardware Level Disable):
    // TODO: If this is done I'll probs need to also
    // periph_module_disable(PERIPH_I2S0_MODULE);

    is2_enabled = false;
}

// @brief: write to i2s data lines
// @param data_buf: Pointer to PCM data buffer.
// @param buf_len: expects length 'data_buf' in BYTES.

/**
 * @brief write to I2S hardware perpheral.
 *
 * @param data_buf Pointer to PCM data buffer.
 *
 * @param buf_len Length of buffer pointed to by 'data_buf'.
 *
 * @return true if successful, false on error
 */
static void esp32_i2s_write(int16_t *data_buf, size_t buf_len)
{
    if (!is2_enabled)
    {
        printf("ERROR: %s i2s channel not enabled, can't write to peripheral\r\n", __func__);
        return;
    }

    if (data_buf == NULL)
    {
        printf("ERROR: %s data_buf NULL \r\n", __func__);
        return;
    }

    printf("ABOUT TO WRITE TO CHANNEL\r\n");

    // This is a blocking function that continues to populate the dma buffers
    // with the data passed into it.
    // NOTE: This function returns when dma buffers are populated, not until
    // the dma buffers are empty.
    // NOTE: dma_buffer_size = dma_frame_num * slot_num * slot_bit_width / 8
    size_t w_bytes;
    esp_err_t ret = i2s_channel_write(
        tx_chan,
        data_buf,
        buf_len,
        &w_bytes,
        portMAX_DELAY);

    // printf("w_bytes = %d \r\n", w_bytes);
    // printf("buf_len = %d \r\n", buf_len);

    if (ret != ESP_OK)
    {
        printf("ERROR: %s failed with Return code: %s (0x%x)\r\n", __func__, esp_err_to_name(ret), ret);
    }

    if (w_bytes != buf_len)
    {
        printf("ERROR: expected number of bytes NOT written\r\n");
    }
}
