#include "i2s.h"
#include "driver/i2s_std.h"


// Sine wave function generator consts
#define SAMPLE_RATE   44000
#define TONE_FREQ     440.0f   // A4
#define AMPLITUDE     0.2f     // 0.0–1.0
// #define EXAMPLE_BUFF_SIZE               88000 // in bytes

// ESP defined GPIO pins used for i2s 1
#define I2S_BCLK_IO1        GPIO_NUM_4      // I2S bit clock io number
#define I2S_WS_IO1          GPIO_NUM_5      // I2S word select io number
#define I2S_DOUT_IO1        GPIO_NUM_18     // I2S data out io number
#define I2S_DIN_IO1         GPIO_NUM_19     // I2S data in io number

// I2S rx channel handler
static i2s_chan_handle_t                rx_chan;

static void esp32_i2s_init(int sample_rate, int bits_per_sample, int channels)
{
    printf("simplex ran \r\n");
    /* Setp 1: Determine the I2S channel configuration and allocate two channels one by one
     * The default configuration can be generated by the helper macro,
     * it only requires the I2S controller id and I2S role
     * The tx and rx channels here are registered on different I2S controller,
     * Except ESP32 and ESP32-S2, others allow to register two separate tx & rx channels on a same controller */
    i2s_chan_config_t tx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));

    /* Step 2: Setting the configurations of standard mode and initialize each channels one by one
     * The slot configuration and clock configuration can be generated by the macros
     * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
     * They can help to specify the slot and clock configurations for initialization or re-configuring */
    i2s_std_config_t tx_std_cfg = {
        .clk_cfg  = I2S_STD_CLK_DEFAULT_CONFIG(sample_rate),
        .slot_cfg = I2S_STD_MSB_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,    // some codecs may require mclk signal, this example doesn't need it
            .bclk = EXAMPLE_STD_BCLK_IO1,
            .ws   = EXAMPLE_STD_WS_IO1,
            .dout = EXAMPLE_STD_DOUT_IO1,
            .din  = EXAMPLE_STD_DIN_IO1, // TOOD: should use the default IO1??
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv   = false,
            },
        },
    };
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &tx_std_cfg));

}

static const i2s_ops_t esp32_i2s_ops = {
    .init = esp32_i2s_init,
};

void i2s_driver_register_esp32(void) {
    i2s_register_ops(&esp32_i2s_ops);
}
